# Generated by Django 3.1.1 on 2020-09-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200912_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image1',
            field=models.ImageField(default='', upload_to='static/school/images'),
        ),
    ]
