# Generated by Django 3.1.1 on 2020-09-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200912_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image10',
            field=models.ImageField(default='', upload_to='school/images/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image2',
            field=models.ImageField(default='', upload_to='school/images/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image3',
            field=models.ImageField(default='', upload_to='school/images/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image4',
            field=models.ImageField(default='', upload_to='school/images/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image5',
            field=models.ImageField(default='', upload_to='school/images/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image6',
            field=models.ImageField(default='', upload_to='school/images/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image7',
            field=models.ImageField(default='', upload_to='school/images/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image8',
            field=models.ImageField(default='', upload_to='school/images/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image9',
            field=models.ImageField(default='', upload_to='school/images/'),
        ),
    ]
