# Generated by Django 3.1.1 on 2020-09-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200912_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(default='', upload_to='school/docs'),
        ),
    ]
